# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' sum from negative binomial density function
NULL

#' sum from Gaussian density function
NULL

lls_rna <- function(mat, bgsub, x, bg, size_dnb) {
    .Call('_InSituType_lls_rna', PACKAGE = 'InSituType', mat, bgsub, x, bg, size_dnb)
}

lls_protein <- function(mat, bgsub, x, xsd) {
    .Call('_InSituType_lls_protein', PACKAGE = 'InSituType', mat, bgsub, x, xsd)
}

